"Filed out from Dolphin Smalltalk 7"!

Object subclass: #BpmGemProcess
	instanceVariableNames: 'name pid port gsSession'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
BpmGemProcess guid: (GUID fromString: '{2238a8ff-db22-4903-8be2-821ea6482294}')!
BpmGemProcess comment: ''!
!BpmGemProcess categoriesForClass!Unclassified! !
!BpmGemProcess methodsFor!

gsSession
	^gsSession!

gsSession: anObject
	gsSession := anObject!

name
	^name!

name: anObject
	name := anObject!

pid
	^pid!

pid: anObject
	pid := anObject!

port
	^port!

port: anObject
	port := anObject! !
!BpmGemProcess categoriesFor: #gsSession!accessing!private! !
!BpmGemProcess categoriesFor: #gsSession:!accessing!private! !
!BpmGemProcess categoriesFor: #name!accessing!private! !
!BpmGemProcess categoriesFor: #name:!accessing!private! !
!BpmGemProcess categoriesFor: #pid!accessing!private! !
!BpmGemProcess categoriesFor: #pid:!accessing!private! !
!BpmGemProcess categoriesFor: #port!accessing!private! !
!BpmGemProcess categoriesFor: #port:!accessing!private! !

